databases:
  - name: soundscapes
    databaseName: soundscapes
    user: soundscapes
    plan: free

services:
  - type: web
    name: soundscapes
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      # AUTOMATICALLY ADDED (OR FIND IT ON RENDER WEBSITE)
      - key: DATABASE_URL
        fromDatabase:
          name: soundscapes
          property: connectionString
      # YOU FIND THIS IN ./config/master.key
      - key: RAILS_MASTER_KEY
        sync: false
