meta_product_name: "[soundScapes]"
meta_title: "[soundScapes] : A collective free background sound application"
meta_description: "'Come listen to sounds with [soundScapes], Stop paying for paid background noise applications when thats all it is, background noise."
meta_image: "webIcon.png"
